development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: b7oomy7miw7onacbheck
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %> 
  host: b7oomy7miw7onacbheck-postgresql.services.clever-cloud.com
  port: 50013